FROM haxe:4.3.4

RUN apt-get update && apt-get install -y --no-install-recommends git python3 curl ca-certificates && rm -rf /var/lib/apt/lists/*

RUN haxelib setup /usr/lib/haxelib && \
    haxelib install flixel 5.6.1 && \
    haxelib install flixel-addons 3.2.2 && \
    haxelib install flixel-tools 1.5.1 && \
    haxelib install tjson 1.4.0 && \
    haxelib install lime 8.1.2 && \
    haxelib install openfl 9.3.3 && \
    haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate 768740a56b26aa0c072720e0d1236b94afe68e3e

WORKDIR /app
